App/routes/main.py
from flask import Blueprint, render_template, session
from App.views import main,helper
from App.schema.schema import UsersSchema

main = Blueprint('main', __name__)


@main.route('/main/', methods=['GET'])
@helper.token_required
def indexmain(current_user, token):
    if token:
        from App.model import users
        user_schema = UsersSchema()
        user = user_schema.dump(current_user)
        session['current_user'] = user
        return render_template('layouts/index.html',current_user=current_user,token=token)

@main.route('/index/', methods=['GET'])
def index():
    user = {}
    session['current_user'] = user
    return render_template('layouts/index.html',current_user=user,token='')



@main.route('/login')
def login():
    return render_template('layouts/login.html')

App/templates/layouts/products/baseproducts.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    {% import 'layouts/head.html' as head %}
    {{ head.head_content('RGMSolutions') }}

    <link rel="stylesheet" href="{{ url_for('static', filename='css/products.css') }}">
</head>
<body>
    <main>
        <nav class="navbar navbar-expand-md  bgpadrao">
            <div class="navbar-collapse collapse w-100 order-0 order-md-0 dual-collapse2">
                <ul class="navbar-nav ">
                    <li class="nav-item ">
                        <a class="nav-link colorlink px-2" href="{{ url_for('main.indexmain',token=token) }}">
                            <span class="glyphicon glyphicon-chevron-left"/>Voltar
                        </a>
                    </li>
                </ul>
            </div>
            <div class="mx-auto order-0">
                <h1 class="navbar-brand mx-2 text-white " >Cadastro de Produtos</h1>
                <button class="navbar-toggler custom-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
                    <span class="navbar-toggler-icon text-white"></span>
                </button>

            </div>

            <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-auto p2">
                        <a class="nav-link colorlink text-center px-2" onclick="btngrupoprod(1,15);" data-toggle="modal" data-target=".modal-groupprod" href="#">
                            Grupo de Produtos
                        </a>
                    </li>


                </ul>
            </div>
        </nav>

        <div id="content" class="container main-container my-2">
            {% block content %} {% endblock %}
        </div>
    </main>


    {% block jsjquery %} {% endblock%}
    {% block jsproduct %} {% endblock %}

</body>
</html>